import type { Operator, Host, Listing, Booking, DamageReport, Review, Conversation, Message, ExternalListing, AnyListing } from '@/types'
import { MOCK_BOOKING_RESULTS, MOCK_BOOKING_CAR_RESULTS } from '@/lib/api/booking-affiliate'

export const MOCK_OPERATOR: Operator = {
  id: 'op-001',
  auth_id: null,
  name: 'CostaSol Car Rent',
  slug: 'costasol-car-rent',
  description: 'Premium car rental in Marbella. Modern fleet, instant confirmation. 0 double bookings since launch.',
  logo_url: null,
  cover_image_url: 'https://images.unsplash.com/photo-1449965408869-eaa3f722e40d?w=800',
  phone: '+34600000000',
  email: 'hello@drivecostasol.com',
  website: 'https://drivecostasol.com',
  address: 'Av. Ricardo Soriano 72, Marbella',
  city: 'Marbella',
  country: 'ES',
  latitude: 36.5101,
  longitude: -4.8824,
  rating: 4.8,
  review_count: 47,
  verified: true,
  active: true,
  stripe_account_id: null,
  stripe_onboarded: false,
  created_at: '2024-01-01T00:00:00Z',
}

export const MOCK_HOST: Host = {
  id: 'host-001',
  auth_id: null,
  name: 'Marco Ferrari',
  bio: "Local Marbella resident. I rent out my car when I'm traveling. Fast responses, flexible pickup!",
  avatar_url: null,
  phone: '+34611222333',
  email: 'marco@example.com',
  city: 'Marbella',
  country: 'ES',
  rating: 4.7,
  review_count: 18,
  verified: true,
  identity_verified: true,
  stripe_account_id: null,
  stripe_onboarded: true,
  response_rate: 98,
  response_time: '30 minutes',
  member_since: '2024-03-15T00:00:00Z',
  total_rentals: 18,
  active: true,
  created_at: '2024-03-15T00:00:00Z',
}

export const MOCK_HOST_LISTING: Listing = {
  id: 'lst-006',
  operator_id: 'op-001',
  host_id: 'host-001',
  owner_type: 'host',
  title: 'Fiat 500 — Cute & Easy to Park',
  description: "Perfect for exploring Marbella's old town. Easy to park everywhere, great AC, full tank on pickup.",
  category: 'car',
  subcategory: null,
  price_per_day: 50,
  price_per_week: 320,
  deposit_amount: 500,
  currency: 'EUR',
  available: true,
  min_rental_days: 1,
  max_rental_days: 30,
  capacity: 4,
  year: 2021,
  make: 'Fiat',
  model: '500',
  color: 'White',
  license_plate: null,
  features: ['AC', 'Bluetooth', 'USB', 'Easy parking'],
  rules: 'No smoking. Return with same fuel level.',
  images: ['https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=800'],
  cover_image_url: 'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=800',
  cancellation_policy: 'flexible',
  instant_book: true,
  pickup_address: 'Marbella Old Town, Málaga',
  latitude: 36.5101,
  longitude: -4.8824,
  rating: 4.7,
  review_count: 18,
  booking_count: 18,
  created_at: new Date().toISOString(),
  host: MOCK_HOST,
}

export const MOCK_LISTINGS: Listing[] = [
  {
    id: 'lst-001',
    operator_id: 'op-001',
    title: 'BMW 3 Series',
    // Mock listings render verbatim when Config.useMock is on, so this demo copy
    // must not make the insurance claim the real product no longer makes.
    description: 'Luxurious BMW 3 Series perfect for exploring the Costa del Sol in style. Optional damage waiver available at checkout.',
    category: 'car',
    subcategory: null,
    price_per_day: 150,
    price_per_week: 950,
    deposit_amount: 1500,
    currency: 'EUR',
    available: true,
    min_rental_days: 1,
    max_rental_days: 30,
    capacity: 5,
    year: 2023,
    make: 'BMW',
    model: '3 Series',
    color: 'Black',
    license_plate: '1234 BCN',
    features: ['AC', 'GPS', 'Bluetooth', 'USB', 'Leather seats'],
    rules: 'No smoking. Full tank return required. Minimum age 21.',
    images: [
      'https://images.unsplash.com/photo-1555215695-3004980ad54e?w=800',
      'https://images.unsplash.com/photo-1503736334956-4c8f8e92946d?w=800',
    ],
    cover_image_url: 'https://images.unsplash.com/photo-1555215695-3004980ad54e?w=800',
    cancellation_policy: 'strict',
    pickup_address: 'Av. Ricardo Soriano 72, Marbella',
    latitude: 36.5101,
    longitude: -4.8824,
    rating: 4.9,
    review_count: 23,
    booking_count: 45,
    created_at: '2024-01-01T00:00:00Z',
    operator: MOCK_OPERATOR,
  },
  {
    id: 'lst-002',
    operator_id: 'op-001',
    title: 'Volkswagen Golf',
    description: 'Reliable and economical VW Golf, great for families and city drives.',
    category: 'car',
    subcategory: null,
    price_per_day: 65,
    price_per_week: 420,
    deposit_amount: 800,
    currency: 'EUR',
    available: true,
    min_rental_days: 1,
    max_rental_days: 30,
    capacity: 5,
    year: 2022,
    make: 'VW',
    model: 'Golf',
    color: 'White',
    license_plate: '5678 MAL',
    features: ['AC', 'Bluetooth', 'USB'],
    rules: 'No smoking. Full tank return required.',
    images: ['https://images.unsplash.com/photo-1471444928139-48c5bf5173f8?w=800'],
    cover_image_url: 'https://images.unsplash.com/photo-1471444928139-48c5bf5173f8?w=800',
    cancellation_policy: 'flexible',
    pickup_address: 'Av. Ricardo Soriano 72, Marbella',
    latitude: 36.5101,
    longitude: -4.8824,
    rating: 4.6,
    review_count: 18,
    booking_count: 62,
    created_at: '2024-01-01T00:00:00Z',
    operator: MOCK_OPERATOR,
  },
  {
    id: 'lst-003',
    operator_id: 'op-001',
    title: 'Audi A3 Convertible',
    description: 'Open-top luxury experience on the Costa del Sol.',
    category: 'car',
    subcategory: null,
    price_per_day: 120,
    price_per_week: 780,
    deposit_amount: 1500,
    currency: 'EUR',
    available: true,
    min_rental_days: 2,
    max_rental_days: 14,
    capacity: 4,
    year: 2023,
    make: 'Audi',
    model: 'A3',
    color: 'Silver',
    license_plate: '9012 MAL',
    features: ['AC', 'GPS', 'Convertible', 'Leather seats'],
    rules: 'No smoking. Minimum age 23.',
    images: ['https://images.unsplash.com/photo-1502877338535-766e1452684a?w=800'],
    cover_image_url: 'https://images.unsplash.com/photo-1502877338535-766e1452684a?w=800',
    cancellation_policy: 'moderate',
    pickup_address: 'Av. Ricardo Soriano 72, Marbella',
    latitude: 36.5201,
    longitude: -4.8724,
    rating: 4.8,
    review_count: 12,
    booking_count: 28,
    created_at: '2024-01-01T00:00:00Z',
    operator: MOCK_OPERATOR,
  },
  {
    id: 'lst-004',
    operator_id: 'op-001',
    title: 'Mercedes C-Class',
    description: 'Top-of-the-line Mercedes for the ultimate comfort experience.',
    category: 'car',
    subcategory: null,
    price_per_day: 175,
    price_per_week: 1100,
    deposit_amount: 2000,
    currency: 'EUR',
    available: true,
    min_rental_days: 1,
    max_rental_days: 30,
    capacity: 5,
    year: 2024,
    make: 'Mercedes',
    model: 'C-Class',
    color: 'Navy',
    license_plate: '3456 MAL',
    features: ['AC', 'GPS', 'Bluetooth', 'USB', 'Leather seats', 'Sunroof'],
    rules: 'No smoking. Full tank return required. Minimum age 25.',
    images: ['https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?w=800'],
    cover_image_url: 'https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?w=800',
    cancellation_policy: 'strict',
    pickup_address: 'Av. Ricardo Soriano 72, Marbella',
    latitude: 36.5001,
    longitude: -4.8924,
    rating: 4.9,
    review_count: 8,
    booking_count: 15,
    created_at: '2024-01-01T00:00:00Z',
    operator: MOCK_OPERATOR,
  },
  {
    id: 'lst-005',
    operator_id: 'op-001',
    title: 'Toyota RAV4',
    description: 'Spacious SUV perfect for family adventures and road trips.',
    category: 'car',
    subcategory: null,
    price_per_day: 95,
    price_per_week: 620,
    deposit_amount: 1000,
    currency: 'EUR',
    available: true,
    min_rental_days: 1,
    max_rental_days: 30,
    capacity: 5,
    year: 2023,
    make: 'Toyota',
    model: 'RAV4',
    color: 'Gray',
    license_plate: '7890 MAL',
    features: ['AC', 'GPS', 'Bluetooth', '4WD', 'USB'],
    rules: 'No smoking. Full tank return required.',
    images: ['https://images.unsplash.com/photo-1617788138017-80ad40651399?w=800'],
    cover_image_url: 'https://images.unsplash.com/photo-1617788138017-80ad40651399?w=800',
    cancellation_policy: 'flexible',
    pickup_address: 'Av. Ricardo Soriano 72, Marbella',
    latitude: 36.5151,
    longitude: -4.8774,
    rating: 4.7,
    review_count: 14,
    booking_count: 33,
    created_at: '2024-01-01T00:00:00Z',
    operator: MOCK_OPERATOR,
  },
  MOCK_HOST_LISTING,
]

const today = new Date()
const tomorrow = new Date(today); tomorrow.setDate(tomorrow.getDate() + 1)
const nextWeek = new Date(today); nextWeek.setDate(nextWeek.getDate() + 7)
const nextWeekPlus3 = new Date(nextWeek); nextWeekPlus3.setDate(nextWeekPlus3.getDate() + 3)
const yesterday = new Date(today); yesterday.setDate(yesterday.getDate() - 1)
const lastWeek = new Date(today); lastWeek.setDate(lastWeek.getDate() - 7)
const lastWeekPlus3 = new Date(lastWeek); lastWeekPlus3.setDate(lastWeekPlus3.getDate() + 3)

function fmtDate(d: Date): string {
  return d.toISOString().split('T')[0]
}

export const MOCK_BOOKINGS: Booking[] = [
  {
    id: 'bk-001',
    listing_id: 'lst-001',
    operator_id: 'op-001',
    user_id: 'usr-001',
    guest_name: 'Marco Ferreira',
    guest_email: 'marco.ferreira@gmail.com',
    guest_phone: '+36701234567',
    guest_nationality: 'HU',
    driver_license_no: 'HU-123456',
    start_date: fmtDate(tomorrow),
    end_date: fmtDate(nextWeek),
    total_days: 6,
    pickup_time: '10:00',
    return_time: '10:00',
    pickup_location: 'Av. Ricardo Soriano 72, Marbella',
    price_per_day: 150,
    subtotal: 900,
    platform_fee: 23,
    total_amount: 923,
    deposit_amount: 1500,
    currency: 'EUR',
    status: 'confirmed',
    payment_status: 'paid',
    payment_intent_id: 'pi_mock_001',
    paid_at: new Date().toISOString(),
    contract_signed_at: null,
    contract_url: null,
    consumer_signature: null,
    operator_signature: null,
    pickup_damage_done: false,
    return_damage_done: false,
    has_damage_claim: false,
    notes: null,
    created_at: new Date().toISOString(),
    listing: MOCK_LISTINGS[0],
    operator: MOCK_OPERATOR,
  },
  {
    id: 'bk-002',
    listing_id: 'lst-002',
    operator_id: 'op-001',
    user_id: 'usr-002',
    guest_name: 'Sophie Laurent',
    guest_email: 'sophie.laurent@gmail.com',
    guest_phone: '+33612345678',
    guest_nationality: 'FR',
    driver_license_no: 'FR-789012',
    start_date: fmtDate(nextWeek),
    end_date: fmtDate(nextWeekPlus3),
    total_days: 3,
    pickup_time: '09:00',
    return_time: '09:00',
    pickup_location: null,
    price_per_day: 65,
    subtotal: 195,
    platform_fee: 5,
    total_amount: 200,
    deposit_amount: 800,
    currency: 'EUR',
    status: 'pending',
    payment_status: 'pending',
    payment_intent_id: null,
    paid_at: null,
    contract_signed_at: null,
    contract_url: null,
    consumer_signature: null,
    operator_signature: null,
    pickup_damage_done: false,
    return_damage_done: false,
    has_damage_claim: false,
    notes: null,
    created_at: new Date().toISOString(),
    listing: MOCK_LISTINGS[1],
    operator: MOCK_OPERATOR,
  },
  {
    id: 'bk-003',
    listing_id: 'lst-003',
    operator_id: 'op-001',
    user_id: 'usr-003',
    guest_name: 'István Kovács',
    guest_email: 'istvan.kovacs@gmail.com',
    guest_phone: '+36701234567',
    guest_nationality: 'HU',
    driver_license_no: 'HU-654321',
    start_date: fmtDate(yesterday),
    end_date: fmtDate(tomorrow),
    total_days: 2,
    pickup_time: '10:00',
    return_time: '10:00',
    pickup_location: null,
    price_per_day: 120,
    subtotal: 240,
    platform_fee: 6,
    total_amount: 246,
    deposit_amount: 1500,
    currency: 'EUR',
    status: 'active',
    payment_status: 'paid',
    payment_intent_id: 'pi_mock_003',
    paid_at: yesterday.toISOString(),
    contract_signed_at: yesterday.toISOString(),
    contract_url: null,
    consumer_signature: null,
    operator_signature: null,
    pickup_damage_done: true,
    return_damage_done: false,
    has_damage_claim: false,
    notes: null,
    created_at: yesterday.toISOString(),
    listing: MOCK_LISTINGS[2],
    operator: MOCK_OPERATOR,
  },
  {
    id: 'bk-004',
    listing_id: 'lst-004',
    operator_id: 'op-001',
    user_id: 'usr-001',
    guest_name: 'Marco Ferreira',
    guest_email: 'marco.ferreira@gmail.com',
    guest_phone: '+36701234567',
    guest_nationality: 'HU',
    driver_license_no: 'HU-123456',
    start_date: fmtDate(lastWeek),
    end_date: fmtDate(lastWeekPlus3),
    total_days: 3,
    pickup_time: '10:00',
    return_time: '10:00',
    pickup_location: null,
    price_per_day: 175,
    subtotal: 525,
    platform_fee: 14,
    total_amount: 539,
    deposit_amount: 2000,
    currency: 'EUR',
    status: 'completed',
    payment_status: 'paid',
    payment_intent_id: 'pi_mock_004',
    paid_at: lastWeek.toISOString(),
    contract_signed_at: lastWeek.toISOString(),
    contract_url: null,
    consumer_signature: null,
    operator_signature: null,
    pickup_damage_done: true,
    return_damage_done: true,
    has_damage_claim: false,
    notes: null,
    created_at: lastWeek.toISOString(),
    listing: MOCK_LISTINGS[3],
    operator: MOCK_OPERATOR,
  },
]

export const MOCK_DAMAGE_REPORT: DamageReport = {
  id: 'dr-001',
  booking_id: 'bk-003',
  listing_id: 'lst-003',
  operator_id: 'op-001',
  type: 'pickup',
  photo_front: 'https://images.unsplash.com/photo-1502877338535-766e1452684a?w=400',
  photo_back: null,
  photo_left: null,
  photo_right: null,
  photo_interior: null,
  photo_extra: null,
  mileage: 45230,
  fuel_level: 'full',
  notes: 'Vehicle in excellent condition.',
  damage_found: false,
  damage_notes: null,
  operator_signed: true,
  consumer_signed: true,
  operator_signature: null,
  consumer_signature: null,
  signed_at: yesterday.toISOString(),
  created_at: yesterday.toISOString(),
}

export const MOCK_REVIEWS: Review[] = [
  {
    id: 'rv-001',
    booking_id: 'bk-004',
    listing_id: 'lst-004',
    operator_id: 'op-001',
    user_id: 'usr-004',
    rating: 5,
    comment: 'Absolutely perfect experience. Car was immaculate, pickup was smooth. CostaSol team was incredibly helpful. Will definitely book again!',
    reply: 'Thank you so much! It was a pleasure having you as our guest. See you next time in Marbella!',
    reply_at: new Date(Date.now() - 86400000).toISOString(),
    created_at: new Date(Date.now() - 172800000).toISOString(),
  },
  {
    id: 'rv-002',
    booking_id: 'bk-005',
    listing_id: 'lst-001',
    operator_id: 'op-001',
    user_id: 'usr-002',
    rating: 4,
    comment: 'Great car, very clean. Pickup was easy. Minor issue with GPS but resolved quickly.',
    reply: null,
    reply_at: null,
    created_at: new Date(Date.now() - 432000000).toISOString(),
  },
  {
    id: 'rv-003',
    booking_id: 'bk-006',
    listing_id: 'lst-002',
    operator_id: 'op-001',
    user_id: 'usr-003',
    rating: 5,
    comment: 'Perfect condition, will book again. Best rental experience I\'ve had in Spain.',
    reply: null,
    reply_at: null,
    created_at: new Date(Date.now() - 864000000).toISOString(),
  },
]

export const MOCK_CONVERSATIONS: Conversation[] = [
  {
    id: 'conv-001',
    booking_id: 'bk-001',
    listing_id: 'lst-001',
    operator_id: 'op-001',
    user_id: 'usr-001',
    guest_name: 'Marco Ferreira',
    last_message: 'What time can I pick up the car?',
    last_message_at: new Date(Date.now() - 3600000).toISOString(),
    unread_consumer: 0,
    unread_operator: 1,
    created_at: new Date().toISOString(),
    listing: MOCK_LISTINGS[0],
    operator: MOCK_OPERATOR,
  },
]

export const MOCK_EXTERNAL_LISTINGS: ExternalListing[] = [
  {
    id: 'ext-host-001',
    connection_id: 'host-airbnb-conn',
    owner_id: 'host-001',
    owner_type: 'host',
    platform: 'airbnb',
    external_id: 'airbnb-99001',
    title: 'Beach Apartment Marbella Old Town',
    description: 'Charming apartment steps from the beach. Fully equipped kitchen, fast WiFi, private terrace.',
    category: 'villa',
    price_per_day: 180,
    currency: 'EUR',
    images: ['https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800'],
    cover_image_url: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800',
    city: 'Marbella',
    country: 'ES',
    latitude: 36.5110,
    longitude: -4.8800,
    external_url: 'https://www.airbnb.com',
    affiliate_url: 'https://www.airbnb.com',
    available: true,
    rating: 4.9,
    review_count: 47,
    ical_url: null,
    last_synced_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
  },
  {
    id: 'ext-host-002',
    connection_id: 'host-turo-conn',
    owner_id: 'host-001',
    owner_type: 'host',
    platform: 'turo',
    external_id: 'turo-55002',
    title: 'Porsche 718 Boxster — Weekend Special',
    description: 'Sport convertible. Perfect for the coastal roads of Andalucia.',
    category: 'car',
    price_per_day: 280,
    currency: 'EUR',
    images: ['https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=800'],
    cover_image_url: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=800',
    city: 'Marbella',
    country: 'ES',
    latitude: 36.5090,
    longitude: -4.8850,
    external_url: 'https://turo.com',
    affiliate_url: 'https://turo.com',
    available: true,
    rating: 4.8,
    review_count: 22,
    ical_url: null,
    last_synced_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
  },
]

export const MOCK_UNIFIED_LISTINGS: AnyListing[] = [
  ...MOCK_LISTINGS.map(l => ({ ...l, sourceType: 'native' as const })),
  ...MOCK_BOOKING_RESULTS.map(l => ({ ...l, sourceType: 'external' as const })),
  ...MOCK_BOOKING_CAR_RESULTS.map(l => ({ ...l, sourceType: 'external' as const })),
  ...MOCK_EXTERNAL_LISTINGS.map(l => ({ ...l, sourceType: 'external' as const })),
]

export const MOCK_MESSAGES: Message[] = [
  {
    id: 'msg-001',
    conversation_id: 'conv-001',
    sender_role: 'system',
    sender_id: null,
    content: 'Booking confirmed. You can now message the operator.',
    read: true,
    created_at: new Date(Date.now() - 7200000).toISOString(),
  },
  {
    id: 'msg-002',
    conversation_id: 'conv-001',
    sender_role: 'consumer',
    sender_id: 'usr-001',
    content: 'What time can I pick up the car?',
    read: true,
    created_at: new Date(Date.now() - 3600000).toISOString(),
  },
  {
    id: 'msg-003',
    conversation_id: 'conv-001',
    sender_role: 'operator',
    sender_id: 'op-001',
    content: 'You can pick up anytime between 8am and 8pm. Just let us know 1 hour before!',
    read: false,
    created_at: new Date(Date.now() - 1800000).toISOString(),
  },
]
