import type { Operator, Listing, Booking, DamageReport, Review, Conversation, Message } from '@/types'

export const MOCK_OPERATOR: Operator = {
  id: 'op-001',
  auth_id: null,
  name: 'CostaSol Car Rent',
  slug: 'costasol-car-rent',
  description: 'Premium car rental in Marbella. Modern fleet, instant confirmation. 0 double bookings since launch.',
  logo_url: null,
  cover_image_url: 'https://images.unsplash.com/photo-1449965408869-eaa3f722e40d?w=800',
  phone: '+34600000000',
  email: 'hello@drivecostasol.com',
  website: 'https://drivecostasol.com',
  address: 'Av. Ricardo Soriano 72, Marbella',
  city: 'Marbella',
  country: 'ES',
  latitude: 36.5101,
  longitude: -4.8824,
  rating: 4.8,
  review_count: 47,
  verified: true,
  active: true,
  stripe_account_id: null,
  stripe_onboarded: false,
  created_at: '2024-01-01T00:00:00Z',
}

export const MOCK_LISTINGS: Listing[] = [
  {
    id: 'lst-001',
    operator_id: 'op-001',
    title: 'BMW 3 Series',
    description: 'Luxurious BMW 3 Series perfect for exploring the Costa del Sol in style. Includes full insurance and 24/7 roadside assistance.',
    category: 'car',
    subcategory: null,
    price_per_day: 8500,
    price_per_week: 52000,
    deposit_amount: 50000,
    currency: 'EUR',
    available: true,
    min_rental_days: 1,
    max_rental_days: 30,
    capacity: 5,
    year: 2023,
    make: 'BMW',
    model: '3 Series',
    color: 'Black',
    license_plate: '1234 BCN',
    features: ['AC', 'GPS', 'Bluetooth', 'USB', 'Leather seats'],
    rules: 'No smoking. Full tank return required. Minimum age 21.',
    images: [
      'https://images.unsplash.com/photo-1555215695-3004980ad54e?w=800',
      'https://images.unsplash.com/photo-1503736334956-4c8f8e92946d?w=800',
    ],
    cover_image_url: 'https://images.unsplash.com/photo-1555215695-3004980ad54e?w=800',
    cancellation_policy: 'strict',
    pickup_address: 'Av. Ricardo Soriano 72, Marbella',
    latitude: 36.5101,
    longitude: -4.8824,
    rating: 4.9,
    review_count: 23,
    booking_count: 45,
    created_at: '2024-01-01T00:00:00Z',
    operator: MOCK_OPERATOR,
  },
  {
    id: 'lst-002',
    operator_id: 'op-001',
    title: 'Volkswagen Golf',
    description: 'Reliable and economical VW Golf, great for families and city drives.',
    category: 'car',
    subcategory: null,
    price_per_day: 4500,
    price_per_week: 27000,
    deposit_amount: 30000,
    currency: 'EUR',
    available: true,
    min_rental_days: 1,
    max_rental_days: 30,
    capacity: 5,
    year: 2022,
    make: 'VW',
    model: 'Golf',
    color: 'White',
    license_plate: '5678 MAL',
    features: ['AC', 'Bluetooth', 'USB'],
    rules: 'No smoking. Full tank return required.',
    images: ['https://images.unsplash.com/photo-1471444928139-48c5bf5173f8?w=800'],
    cover_image_url: 'https://images.unsplash.com/photo-1471444928139-48c5bf5173f8?w=800',
    cancellation_policy: 'flexible',
    pickup_address: 'Av. Ricardo Soriano 72, Marbella',
    latitude: 36.5101,
    longitude: -4.8824,
    rating: 4.6,
    review_count: 18,
    booking_count: 62,
    created_at: '2024-01-01T00:00:00Z',
    operator: MOCK_OPERATOR,
  },
  {
    id: 'lst-003',
    operator_id: 'op-001',
    title: 'Audi A3 Convertible',
    description: 'Open-top luxury experience on the Costa del Sol.',
    category: 'car',
    subcategory: null,
    price_per_day: 7500,
    price_per_week: 46000,
    deposit_amount: 50000,
    currency: 'EUR',
    available: true,
    min_rental_days: 2,
    max_rental_days: 14,
    capacity: 4,
    year: 2023,
    make: 'Audi',
    model: 'A3',
    color: 'Silver',
    license_plate: '9012 MAL',
    features: ['AC', 'GPS', 'Convertible', 'Leather seats'],
    rules: 'No smoking. Minimum age 23.',
    images: ['https://images.unsplash.com/photo-1502877338535-766e1452684a?w=800'],
    cover_image_url: 'https://images.unsplash.com/photo-1502877338535-766e1452684a?w=800',
    cancellation_policy: 'moderate',
    pickup_address: 'Av. Ricardo Soriano 72, Marbella',
    latitude: 36.5201,
    longitude: -4.8724,
    rating: 4.8,
    review_count: 12,
    booking_count: 28,
    created_at: '2024-01-01T00:00:00Z',
    operator: MOCK_OPERATOR,
  },
  {
    id: 'lst-004',
    operator_id: 'op-001',
    title: 'Mercedes C-Class',
    description: 'Top-of-the-line Mercedes for the ultimate comfort experience.',
    category: 'car',
    subcategory: null,
    price_per_day: 9500,
    price_per_week: 59000,
    deposit_amount: 60000,
    currency: 'EUR',
    available: true,
    min_rental_days: 1,
    max_rental_days: 30,
    capacity: 5,
    year: 2024,
    make: 'Mercedes',
    model: 'C-Class',
    color: 'Navy',
    license_plate: '3456 MAL',
    features: ['AC', 'GPS', 'Bluetooth', 'USB', 'Leather seats', 'Sunroof'],
    rules: 'No smoking. Full tank return required. Minimum age 25.',
    images: ['https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?w=800'],
    cover_image_url: 'https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?w=800',
    cancellation_policy: 'strict',
    pickup_address: 'Av. Ricardo Soriano 72, Marbella',
    latitude: 36.5001,
    longitude: -4.8924,
    rating: 4.9,
    review_count: 8,
    booking_count: 15,
    created_at: '2024-01-01T00:00:00Z',
    operator: MOCK_OPERATOR,
  },
  {
    id: 'lst-005',
    operator_id: 'op-001',
    title: 'Toyota RAV4',
    description: 'Spacious SUV perfect for family adventures and road trips.',
    category: 'car',
    subcategory: null,
    price_per_day: 6500,
    price_per_week: 40000,
    deposit_amount: 40000,
    currency: 'EUR',
    available: true,
    min_rental_days: 1,
    max_rental_days: 30,
    capacity: 5,
    year: 2023,
    make: 'Toyota',
    model: 'RAV4',
    color: 'Gray',
    license_plate: '7890 MAL',
    features: ['AC', 'GPS', 'Bluetooth', '4WD', 'USB'],
    rules: 'No smoking. Full tank return required.',
    images: ['https://images.unsplash.com/photo-1617788138017-80ad40651399?w=800'],
    cover_image_url: 'https://images.unsplash.com/photo-1617788138017-80ad40651399?w=800',
    cancellation_policy: 'flexible',
    pickup_address: 'Av. Ricardo Soriano 72, Marbella',
    latitude: 36.5151,
    longitude: -4.8774,
    rating: 4.7,
    review_count: 14,
    booking_count: 33,
    created_at: '2024-01-01T00:00:00Z',
    operator: MOCK_OPERATOR,
  },
]

const today = new Date()
const tomorrow = new Date(today); tomorrow.setDate(tomorrow.getDate() + 1)
const nextWeek = new Date(today); nextWeek.setDate(nextWeek.getDate() + 7)
const nextWeekPlus3 = new Date(nextWeek); nextWeekPlus3.setDate(nextWeekPlus3.getDate() + 3)
const yesterday = new Date(today); yesterday.setDate(yesterday.getDate() - 1)
const lastWeek = new Date(today); lastWeek.setDate(lastWeek.getDate() - 7)
const lastWeekPlus3 = new Date(lastWeek); lastWeekPlus3.setDate(lastWeekPlus3.getDate() + 3)

function fmtDate(d: Date): string {
  return d.toISOString().split('T')[0]
}

export const MOCK_BOOKINGS: Booking[] = [
  {
    id: 'bk-001',
    listing_id: 'lst-001',
    operator_id: 'op-001',
    user_id: 'usr-001',
    guest_name: 'Test User',
    guest_email: 'test@example.com',
    guest_phone: '+36701234567',
    guest_nationality: 'HU',
    driver_license_no: 'HU-123456',
    start_date: fmtDate(tomorrow),
    end_date: fmtDate(nextWeek),
    total_days: 6,
    pickup_time: '10:00',
    return_time: '10:00',
    pickup_location: 'Av. Ricardo Soriano 72, Marbella',
    price_per_day: 8500,
    subtotal: 51000,
    platform_fee: 1275,
    total_amount: 52275,
    deposit_amount: 50000,
    currency: 'EUR',
    status: 'confirmed',
    payment_status: 'paid',
    payment_intent_id: 'pi_mock_001',
    paid_at: new Date().toISOString(),
    contract_signed_at: null,
    contract_url: null,
    consumer_signature: null,
    operator_signature: null,
    pickup_damage_done: false,
    return_damage_done: false,
    has_damage_claim: false,
    notes: null,
    created_at: new Date().toISOString(),
    listing: MOCK_LISTINGS[0],
    operator: MOCK_OPERATOR,
  },
  {
    id: 'bk-002',
    listing_id: 'lst-002',
    operator_id: 'op-001',
    user_id: 'usr-001',
    guest_name: 'Test User',
    guest_email: 'test@example.com',
    guest_phone: '+36701234567',
    guest_nationality: 'HU',
    driver_license_no: 'HU-123456',
    start_date: fmtDate(nextWeek),
    end_date: fmtDate(nextWeekPlus3),
    total_days: 3,
    pickup_time: '09:00',
    return_time: '09:00',
    pickup_location: null,
    price_per_day: 4500,
    subtotal: 13500,
    platform_fee: 338,
    total_amount: 13838,
    deposit_amount: 30000,
    currency: 'EUR',
    status: 'pending',
    payment_status: 'pending',
    payment_intent_id: null,
    paid_at: null,
    contract_signed_at: null,
    contract_url: null,
    consumer_signature: null,
    operator_signature: null,
    pickup_damage_done: false,
    return_damage_done: false,
    has_damage_claim: false,
    notes: null,
    created_at: new Date().toISOString(),
    listing: MOCK_LISTINGS[1],
    operator: MOCK_OPERATOR,
  },
  {
    id: 'bk-003',
    listing_id: 'lst-003',
    operator_id: 'op-001',
    user_id: 'usr-001',
    guest_name: 'Test User',
    guest_email: 'test@example.com',
    guest_phone: '+36701234567',
    guest_nationality: 'HU',
    driver_license_no: 'HU-123456',
    start_date: fmtDate(yesterday),
    end_date: fmtDate(tomorrow),
    total_days: 2,
    pickup_time: '10:00',
    return_time: '10:00',
    pickup_location: null,
    price_per_day: 7500,
    subtotal: 15000,
    platform_fee: 375,
    total_amount: 15375,
    deposit_amount: 50000,
    currency: 'EUR',
    status: 'active',
    payment_status: 'paid',
    payment_intent_id: 'pi_mock_003',
    paid_at: yesterday.toISOString(),
    contract_signed_at: yesterday.toISOString(),
    contract_url: null,
    consumer_signature: null,
    operator_signature: null,
    pickup_damage_done: true,
    return_damage_done: false,
    has_damage_claim: false,
    notes: null,
    created_at: yesterday.toISOString(),
    listing: MOCK_LISTINGS[2],
    operator: MOCK_OPERATOR,
  },
  {
    id: 'bk-004',
    listing_id: 'lst-004',
    operator_id: 'op-001',
    user_id: 'usr-001',
    guest_name: 'Test User',
    guest_email: 'test@example.com',
    guest_phone: '+36701234567',
    guest_nationality: 'HU',
    driver_license_no: 'HU-123456',
    start_date: fmtDate(lastWeek),
    end_date: fmtDate(lastWeekPlus3),
    total_days: 3,
    pickup_time: '10:00',
    return_time: '10:00',
    pickup_location: null,
    price_per_day: 9500,
    subtotal: 28500,
    platform_fee: 713,
    total_amount: 29213,
    deposit_amount: 60000,
    currency: 'EUR',
    status: 'completed',
    payment_status: 'paid',
    payment_intent_id: 'pi_mock_004',
    paid_at: lastWeek.toISOString(),
    contract_signed_at: lastWeek.toISOString(),
    contract_url: null,
    consumer_signature: null,
    operator_signature: null,
    pickup_damage_done: true,
    return_damage_done: true,
    has_damage_claim: false,
    notes: null,
    created_at: lastWeek.toISOString(),
    listing: MOCK_LISTINGS[3],
    operator: MOCK_OPERATOR,
  },
]

export const MOCK_DAMAGE_REPORT: DamageReport = {
  id: 'dr-001',
  booking_id: 'bk-003',
  listing_id: 'lst-003',
  operator_id: 'op-001',
  type: 'pickup',
  photo_front: 'https://images.unsplash.com/photo-1502877338535-766e1452684a?w=400',
  photo_back: null,
  photo_left: null,
  photo_right: null,
  photo_interior: null,
  photo_extra: null,
  mileage: 45230,
  fuel_level: 'full',
  notes: 'Vehicle in excellent condition.',
  damage_found: false,
  damage_notes: null,
  operator_signed: true,
  consumer_signed: true,
  operator_signature: null,
  consumer_signature: null,
  signed_at: yesterday.toISOString(),
  created_at: yesterday.toISOString(),
}

export const MOCK_REVIEWS: Review[] = [
  {
    id: 'rv-001',
    booking_id: 'bk-004',
    listing_id: 'lst-004',
    operator_id: 'op-001',
    user_id: 'usr-001',
    rating: 5,
    comment: 'Absolutely perfect experience. Car was immaculate, pickup was smooth. CostaSol team was incredibly helpful. Will definitely book again!',
    reply: 'Thank you so much! It was a pleasure having you as our guest. See you next time in Marbella! 🌊',
    reply_at: new Date(Date.now() - 86400000).toISOString(),
    created_at: new Date(Date.now() - 172800000).toISOString(),
  },
  {
    id: 'rv-002',
    booking_id: 'bk-005',
    listing_id: 'lst-001',
    operator_id: 'op-001',
    user_id: null,
    rating: 4,
    comment: 'Great car, very clean. Pickup was easy. Minor issue with GPS but resolved quickly.',
    reply: null,
    reply_at: null,
    created_at: new Date(Date.now() - 432000000).toISOString(),
  },
]

export const MOCK_CONVERSATIONS: Conversation[] = [
  {
    id: 'conv-001',
    booking_id: 'bk-001',
    listing_id: 'lst-001',
    operator_id: 'op-001',
    user_id: 'usr-001',
    guest_name: 'Test User',
    last_message: 'What time can I pick up the car?',
    last_message_at: new Date(Date.now() - 3600000).toISOString(),
    unread_consumer: 0,
    unread_operator: 1,
    created_at: new Date().toISOString(),
    listing: MOCK_LISTINGS[0],
    operator: MOCK_OPERATOR,
  },
]

export const MOCK_MESSAGES: Message[] = [
  {
    id: 'msg-001',
    conversation_id: 'conv-001',
    sender_role: 'system',
    sender_id: null,
    content: 'Booking confirmed. You can now message the operator.',
    read: true,
    created_at: new Date(Date.now() - 7200000).toISOString(),
  },
  {
    id: 'msg-002',
    conversation_id: 'conv-001',
    sender_role: 'consumer',
    sender_id: 'usr-001',
    content: 'What time can I pick up the car?',
    read: true,
    created_at: new Date(Date.now() - 3600000).toISOString(),
  },
  {
    id: 'msg-003',
    conversation_id: 'conv-001',
    sender_role: 'operator',
    sender_id: 'op-001',
    content: 'You can pick up anytime between 8am and 8pm. Just let us know 1 hour before!',
    read: false,
    created_at: new Date(Date.now() - 1800000).toISOString(),
  },
]
